# Makefile for fireTemp micro-agent
TOPDIR = ../..
include $(TOPDIR)/config.mak
include $(TOPDIR)/applications/config.mak

AGENT = pc3ChildAgent
OBJS = pc3ChildAgent.o

include $(TOPDIR)/applications/Rules.mak
