# Makefile for fireTemp micro-agent
TOPDIR = ../..
include $(TOPDIR)/config.mak
include $(TOPDIR)/applications/config.mak

AGENT = pc1RootAgent
OBJS = pc1RootAgent.o

include $(TOPDIR)/applications/Rules.mak
