# Makefile for fireTemp micro-agent
TOPDIR = ../..
include $(TOPDIR)/config.mak
include $(TOPDIR)/applications/config.mak

AGENT = pc4RootAgent
OBJS = pc4RootAgent.o

include $(TOPDIR)/applications/Rules.mak
