# Makefile for fireTemp micro-agent
TOPDIR = ../..
include $(TOPDIR)/config.mak
include $(TOPDIR)/applications/config.mak

AGENT = pc3RootAgent
OBJS = pc3RootAgent.o

include $(TOPDIR)/applications/Rules.mak
