# Makefile for fireTemp micro-agent
TOPDIR = ../..
include $(TOPDIR)/config.mak
include $(TOPDIR)/applications/config.mak

AGENT = pc6ChildAgent
OBJS = pc6ChildAgent.o

include $(TOPDIR)/applications/Rules.mak
