# Makefile for fireTemp micro-agent
TOPDIR = ../..
include $(TOPDIR)/config.mak
include $(TOPDIR)/applications/config.mak

AGENT = pc6RootAgent
OBJS = pc6RootAgent.o

include $(TOPDIR)/applications/Rules.mak
