# Makefile for fireTemp micro-agent
TOPDIR = ../..
include $(TOPDIR)/config.mak
include $(TOPDIR)/applications/config.mak

AGENT = pc4ChildAgent
OBJS = pc4ChildAgent.o

include $(TOPDIR)/applications/Rules.mak
