# Makefile for fireTemp micro-agent
TOPDIR = ../..
include $(TOPDIR)/config.mak
include $(TOPDIR)/applications/config.mak

AGENT = pc2ChildAgent
OBJS = pc2ChildAgent.o

include $(TOPDIR)/applications/Rules.mak
